### ISSUE TITLE
Add Questionnaire pages

### ISSUE THREAD

**Issue by Steven-Hsu1** [BigDataForSanDiego/Team-124#1]
## Issue Description

Need pages for questionnaire

## Required

Follow [Figma](https://www.figma.com/design/q1jBEOCtSmyxEAPYjoqHH8/Fadi-Elia's-team-library?node-id=2320-386&node-type=frame&t=mqHW2eJZz2CTJIg4-0) design.

**Comment by emilioece** [comment]
### Update on Issue: Add Questionnaire Pages #1

I have completed the questionnaire with four pages:

1. **Basic Information**
2. **Demographics**
3. **Issues**
4. **Therapist Preferences**

Next steps:
- Add a photo to the index page.
- Potentially add a background for all pages.
- Include an icebreaker page.

Let me know if you have any feedback or additional requests!
